-- ============================================================
-- 1. ESTRUTURA DAS TABELAS (Garante que existem)
-- ============================================================

-- Tabela de Perfis
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  avatar_url TEXT,
  banner_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela da Biblioteca
CREATE TABLE IF NOT EXISTS biblioteca_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  obra_id INTEGER NOT NULL,
  obr_nome TEXT,
  obr_imagem TEXT,
  data_adicionada TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- 2. RESETAR POLÍTICAS DE SEGURANÇA (RLS)
-- ============================================================

-- Habilita RLS nas tabelas
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE biblioteca_usuario ENABLE ROW LEVEL SECURITY;

-- Remove políticas antigas para evitar conflitos
DROP POLICY IF EXISTS "Public profiles" ON user_profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can manage their library" ON biblioteca_usuario;

-- ============================================================
-- 3. CRIAR NOVAS POLÍTICAS (Permissões)
-- ============================================================

-- PERFIL: Todo mundo pode ler (para ver avatar/nome)
CREATE POLICY "Public profiles" 
ON user_profiles FOR SELECT 
USING (true);

-- PERFIL: Usuário pode CRIAR seu próprio perfil
CREATE POLICY "Users can insert their own profile" 
ON user_profiles FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- PERFIL: Usuário pode ATUALIZAR seu próprio perfil
CREATE POLICY "Users can update their own profile" 
ON user_profiles FOR UPDATE 
USING (auth.uid() = user_id);

-- BIBLIOTECA: Usuário pode fazer TUDO (Ler, Criar, Deletar) apenas na sua própria biblioteca
CREATE POLICY "Users can manage their library" 
ON biblioteca_usuario 
USING (auth.uid() = usuario_id);

-- ============================================================
-- 4. BUCKETS DE STORAGE (Imagens)
-- ============================================================
-- Insere os buckets se não existirem (requer extensão 'storage' ativada)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('banners', 'banners', true)
ON CONFLICT (id) DO NOTHING;

-- Política de Storage: Permitir acesso público para leitura
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id IN ('avatars', 'banners') );

-- Política de Storage: Usuário logado pode fazer upload
DROP POLICY IF EXISTS "Auth Users Upload" ON storage.objects;
CREATE POLICY "Auth Users Upload"
ON storage.objects FOR INSERT
WITH CHECK ( auth.role() = 'authenticated' AND bucket_id IN ('avatars', 'banners') );
